# This file has been generated by node2nix 1.0.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, commonBuildInputs ? []}:

let
  sources = {
    "simple-xmpp-1.3.0" = {
      name = "simple-xmpp";
      packageName = "simple-xmpp";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-xmpp/-/simple-xmpp-1.3.0.tgz";
        sha1 = "b077c72151e0f5929bc9a93e1fee7cb2284282cb";
      };
    };
    "node-xmpp-client-3.0.2" = {
      name = "node-xmpp-client";
      packageName = "node-xmpp-client";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-xmpp-client/-/node-xmpp-client-3.0.2.tgz";
        sha1 = "0202bc8a8a03bd2a8223006ffb1d5057fa1b79d6";
      };
    };
    "qbox-0.1.7" = {
      name = "qbox";
      packageName = "qbox";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/qbox/-/qbox-0.1.7.tgz";
        sha1 = "e80f0dc5d09f869d8882168c3f66ac8dd2840f02";
      };
    };
    "browser-request-0.3.3" = {
      name = "browser-request";
      packageName = "browser-request";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-request/-/browser-request-0.3.3.tgz";
        sha1 = "9ece5b5aca89a29932242e18bf933def9876cc17";
      };
    };
    "debug-2.2.0" = {
      name = "debug";
      packageName = "debug";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.2.0.tgz";
        sha1 = "f87057e995b1a1f6ae6a4960664137bc56f039da";
      };
    };
    "md5.js-1.3.4" = {
      name = "md5.js";
      packageName = "md5.js";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/md5.js/-/md5.js-1.3.4.tgz";
        sha1 = "e9bdbde94a20a5ac18b04340fc5764d5b09d901d";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "node-xmpp-core-5.0.2" = {
      name = "node-xmpp-core";
      packageName = "node-xmpp-core";
      version = "5.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-xmpp-core/-/node-xmpp-core-5.0.2.tgz";
        sha1 = "17603b38753e7d97a9bc866ceabc637fcd5a7b8b";
      };
    };
    "request-2.74.0" = {
      name = "request";
      packageName = "request";
      version = "2.74.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.74.0.tgz";
        sha1 = "7693ca768bbb0ea5c8ce08c084a45efa05b892ab";
      };
    };
    "ws-1.1.1" = {
      name = "ws";
      packageName = "ws";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-1.1.1.tgz";
        sha1 = "082ddb6c641e85d4bb451f03d52f06eabdb1f018";
      };
    };
    "ms-0.7.1" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.1.tgz";
        sha1 = "9cd13c03adbff25b65effde7ce864ee952017098";
      };
    };
    "hash-base-3.0.3" = {
      name = "hash-base";
      packageName = "hash-base";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hash-base/-/hash-base-3.0.3.tgz";
        sha1 = "87ec48734bfe354275535150b14821566b083807";
      };
    };
    "inherits-2.0.1" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz";
        sha1 = "b17d08d326b4423e568eff719f91b0b1cbdf69f1";
      };
    };
    "lodash.assign-4.2.0" = {
      name = "lodash.assign";
      packageName = "lodash.assign";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.assign/-/lodash.assign-4.2.0.tgz";
        sha1 = "0d99f3ccd7a6d261d19bdaeb9245005d285808e7";
      };
    };
    "ltx-2.4.2" = {
      name = "ltx";
      packageName = "ltx";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ltx/-/ltx-2.4.2.tgz";
        sha1 = "0586d942161290589adb127b19a30e7f0f84d9ad";
      };
    };
    "node-xmpp-jid-2.3.0" = {
      name = "node-xmpp-jid";
      packageName = "node-xmpp-jid";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-xmpp-jid/-/node-xmpp-jid-2.3.0.tgz";
        sha1 = "60a3c950582a0cdcfda074494357a85178f38878";
      };
    };
    "node-xmpp-stanza-1.1.0" = {
      name = "node-xmpp-stanza";
      packageName = "node-xmpp-stanza";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-xmpp-stanza/-/node-xmpp-stanza-1.1.0.tgz";
        sha1 = "26bb749065fe00787004f8c3b7c0b28494d46554";
      };
    };
    "reconnect-core-https://codeload.github.com/dodo/reconnect-core/legacy.tar.gz/merged" = {
      name = "reconnect-core";
      packageName = "reconnect-core";
      version = "0.0.1";
      src = fetchurl {
        name = "reconnect-core-0.0.1.tar.gz";
        url = https://codeload.github.com/dodo/reconnect-core/legacy.tar.gz/merged;
        sha256 = "431dd7a1578061815270e4ad59c6e8b40dff6b308244973e1c11049ccbf1629b";
      };
    };
    "node-xmpp-tls-connect-1.0.1" = {
      name = "node-xmpp-tls-connect";
      packageName = "node-xmpp-tls-connect";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-xmpp-tls-connect/-/node-xmpp-tls-connect-1.0.1.tgz";
        sha1 = "91ace43ac26b138861b2be478df9df19d61dc5c3";
      };
    };
    "backoff-2.3.0" = {
      name = "backoff";
      packageName = "backoff";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/backoff/-/backoff-2.3.0.tgz";
        sha1 = "ee7c7e38093f92e472859db635e7652454fc21ea";
      };
    };
    "aws-sign2-0.6.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.6.0.tgz";
        sha1 = "14342dd38dbcc94d0e5b87d763cd63612c0e794f";
      };
    };
    "aws4-1.4.1" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.4.1.tgz";
        sha1 = "fde7d5292466d230e5ee0f4e038d9dfaab08fc61";
      };
    };
    "bl-1.1.2" = {
      name = "bl";
      packageName = "bl";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bl/-/bl-1.1.2.tgz";
        sha1 = "fdca871a99713aa00d19e3bbba41c44787a65398";
      };
    };
    "caseless-0.11.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.11.0.tgz";
        sha1 = "715b96ea9841593cc33067923f5ec60ebda4f7d7";
      };
    };
    "combined-stream-1.0.5" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.5.tgz";
        sha1 = "938370a57b4a51dea2c77c15d5c5fdf895164009";
      };
    };
    "extend-3.0.0" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.0.tgz";
        sha1 = "5a474353b9f3353ddd8176dfd37b91c83a46f1d4";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-1.0.1" = {
      name = "form-data";
      packageName = "form-data";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-1.0.1.tgz";
        sha1 = "ae315db9a4907fa065502304a66d7733475ee37c";
      };
    };
    "har-validator-2.0.6" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-2.0.6.tgz";
        sha1 = "cdcbc08188265ad119b6a5a7c8ab70eecfb5d27d";
      };
    };
    "hawk-3.1.3" = {
      name = "hawk";
      packageName = "hawk";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hawk/-/hawk-3.1.3.tgz";
        sha1 = "078444bd7c1640b0fe540d2c9b73d59678e8e1c4";
      };
    };
    "http-signature-1.1.1" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.1.1.tgz";
        sha1 = "df72e267066cd0ac67fb76adf8e134a8fbcf91bf";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "mime-types-2.1.11" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.11.tgz";
        sha1 = "c259c471bda808a85d6cd193b430a5fae4473b3c";
      };
    };
    "node-uuid-1.4.7" = {
      name = "node-uuid";
      packageName = "node-uuid";
      version = "1.4.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.7.tgz";
        sha1 = "6da5a17668c4b3dd59623bda11cf7fa4c1f60a6f";
      };
    };
    "oauth-sign-0.8.2" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.8.2.tgz";
        sha1 = "46a6ab7f0aead8deae9ec0565780b7d4efeb9d43";
      };
    };
    "qs-6.2.1" = {
      name = "qs";
      packageName = "qs";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.2.1.tgz";
        sha1 = "ce03c5ff0935bc1d9d69a9f14cbd18e568d67625";
      };
    };
    "stringstream-0.0.5" = {
      name = "stringstream";
      packageName = "stringstream";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz";
        sha1 = "4e484cd4de5a0bbbee18e46307710a8a81621878";
      };
    };
    "tough-cookie-2.3.1" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.3.1.tgz";
        sha1 = "99c77dfbb7d804249e8a299d4cb0fd81fef083fd";
      };
    };
    "tunnel-agent-0.4.3" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.4.3.tgz";
        sha1 = "6373db76909fe570e08d73583365ed828a74eeeb";
      };
    };
    "readable-stream-2.0.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.0.6.tgz";
        sha1 = "8f90341e68a53ccc928788dacfcd11b36eb9b78e";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "process-nextick-args-1.0.7" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz";
        sha1 = "150e20b756590ad3f91093f25a4f2ad8bff30ba3";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "async-2.0.1" = {
      name = "async";
      packageName = "async";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.0.1.tgz";
        sha1 = "b709cc0280a9c36f09f4536be823c838a9049e25";
      };
    };
    "lodash-4.15.0" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.15.0.tgz";
        sha1 = "3162391d8f0140aa22cf8f6b3c34d6b7f63d3aa9";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "commander-2.9.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.9.0.tgz";
        sha1 = "9c99094176e12240cb22d6c5146098400fe0f7d4";
      };
    };
    "is-my-json-valid-2.13.1" = {
      name = "is-my-json-valid";
      packageName = "is-my-json-valid";
      version = "2.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-my-json-valid/-/is-my-json-valid-2.13.1.tgz";
        sha1 = "d55778a82feb6b0963ff4be111d5d1684e890707";
      };
    };
    "pinkie-promise-2.0.1" = {
      name = "pinkie-promise";
      packageName = "pinkie-promise";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz";
        sha1 = "2135d6dfa7a358c069ac9b178776288228450ffa";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "ansi-regex-2.0.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.0.0.tgz";
        sha1 = "c5061b6e0ef8a81775e50f5d66151bf6bf371107";
      };
    };
    "graceful-readlink-1.0.1" = {
      name = "graceful-readlink";
      packageName = "graceful-readlink";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-readlink/-/graceful-readlink-1.0.1.tgz";
        sha1 = "4cafad76bc62f02fa039b2f94e9a3dd3a391a725";
      };
    };
    "generate-function-2.0.0" = {
      name = "generate-function";
      packageName = "generate-function";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/generate-function/-/generate-function-2.0.0.tgz";
        sha1 = "6858fe7c0969b7d4e9093337647ac79f60dfbe74";
      };
    };
    "generate-object-property-1.2.0" = {
      name = "generate-object-property";
      packageName = "generate-object-property";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/generate-object-property/-/generate-object-property-1.2.0.tgz";
        sha1 = "9c0e1c40308ce804f4783618b937fa88f99d50d0";
      };
    };
    "jsonpointer-2.0.0" = {
      name = "jsonpointer";
      packageName = "jsonpointer";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonpointer/-/jsonpointer-2.0.0.tgz";
        sha1 = "3af1dd20fe85463910d469a385e33017d2a030d9";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
    "is-property-1.0.2" = {
      name = "is-property";
      packageName = "is-property";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-property/-/is-property-1.0.2.tgz";
        sha1 = "57fe1c4e48474edd65b09911f26b1cd4095dda84";
      };
    };
    "pinkie-2.0.4" = {
      name = "pinkie";
      packageName = "pinkie";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie/-/pinkie-2.0.4.tgz";
        sha1 = "72556b80cfa0d48a974e80e77248e80ed4f7f870";
      };
    };
    "hoek-2.16.3" = {
      name = "hoek";
      packageName = "hoek";
      version = "2.16.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoek/-/hoek-2.16.3.tgz";
        sha1 = "20bb7403d3cea398e91dc4710a8ff1b8274a25ed";
      };
    };
    "boom-2.10.1" = {
      name = "boom";
      packageName = "boom";
      version = "2.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-2.10.1.tgz";
        sha1 = "39c8918ceff5799f83f9492a848f625add0c766f";
      };
    };
    "cryptiles-2.0.5" = {
      name = "cryptiles";
      packageName = "cryptiles";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cryptiles/-/cryptiles-2.0.5.tgz";
        sha1 = "3bdfecdc608147c1c67202fa291e7dca59eaa3b8";
      };
    };
    "sntp-1.0.9" = {
      name = "sntp";
      packageName = "sntp";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/sntp/-/sntp-1.0.9.tgz";
        sha1 = "6541184cc90aeea6c6e7b35e2659082443c66198";
      };
    };
    "assert-plus-0.2.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-0.2.0.tgz";
        sha1 = "d74e1b87e7affc0db8aadb7021f3fe48101ab234";
      };
    };
    "jsprim-1.3.0" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.3.0.tgz";
        sha1 = "ce2e1bef835204b4f3099928c602f8b6ae615650";
      };
    };
    "sshpk-1.10.0" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.10.0.tgz";
        sha1 = "104d6ba2afb2ac099ab9567c0d193977f29c6dfa";
      };
    };
    "extsprintf-1.0.2" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.0.2.tgz";
        sha1 = "e1080e0658e300b06294990cc70e1502235fd550";
      };
    };
    "json-schema-0.2.2" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.2.tgz";
        sha1 = "50354f19f603917c695f70b85afa77c3b0f23506";
      };
    };
    "verror-1.3.6" = {
      name = "verror";
      packageName = "verror";
      version = "1.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.3.6.tgz";
        sha1 = "cff5df12946d297d2baaefaa2689e25be01c005c";
      };
    };
    "asn1-0.2.3" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz";
        sha1 = "dac8787713c9966849fc8180777ebe9c1ddf3b86";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "dashdash-1.14.0" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.0.tgz";
        sha1 = "29e486c5418bf0f356034a993d51686a33e84141";
      };
    };
    "getpass-0.1.6" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.6.tgz";
        sha1 = "283ffd9fc1256840875311c1b60e8c40187110e6";
      };
    };
    "jsbn-0.1.0" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.0.tgz";
        sha1 = "650987da0dd74f4ebf5a11377a2aa2d273e97dfd";
      };
    };
    "tweetnacl-0.13.3" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.13.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.13.3.tgz";
        sha1 = "d628b56f3bcc3d5ae74ba9d4c1a704def5ab4b56";
      };
    };
    "jodid25519-1.0.2" = {
      name = "jodid25519";
      packageName = "jodid25519";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jodid25519/-/jodid25519-1.0.2.tgz";
        sha1 = "06d4912255093419477d425633606e0e90782967";
      };
    };
    "ecc-jsbn-0.1.1" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.1.tgz";
        sha1 = "0fc73a9ed5f0d53c38193398523ef7e543777505";
      };
    };
    "bcrypt-pbkdf-1.0.0" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.0.tgz";
        sha1 = "3ca76b85241c7170bf7d9703e7b9aa74630040d4";
      };
    };
    "tweetnacl-0.14.3" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.3.tgz";
        sha1 = "3da382f670f25ded78d7b3d1792119bca0b7132d";
      };
    };
    "mime-db-1.23.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.23.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.23.0.tgz";
        sha1 = "a31b4070adaea27d732ea333740a64d0ec9a6659";
      };
    };
    "options-0.0.6" = {
      name = "options";
      packageName = "options";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/options/-/options-0.0.6.tgz";
        sha1 = "ec22d312806bb53e731773e7cdaefcf1c643128f";
      };
    };
    "ultron-1.0.2" = {
      name = "ultron";
      packageName = "ultron";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ultron/-/ultron-1.0.2.tgz";
        sha1 = "ace116ab557cd197386a4e88f4685378c8b2e4fa";
      };
    };
    "adm-zip-0.4.7" = {
      name = "adm-zip";
      packageName = "adm-zip";
      version = "0.4.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/adm-zip/-/adm-zip-0.4.7.tgz";
        sha1 = "8606c2cbf1c426ce8c8ec00174447fd49b6eafc1";
      };
    };
    "bluebird-2.11.0" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "2.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-2.11.0.tgz";
        sha1 = "534b9033c022c9579c56ba3b3e5a5caafbb650e1";
      };
    };
    "browserify-11.2.0" = {
      name = "browserify";
      packageName = "browserify";
      version = "11.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify/-/browserify-11.2.0.tgz";
        sha1 = "a11bb9dd209d79572b813f7eeeaf828a5f5c0e4e";
      };
    };
    "guid-0.0.12" = {
      name = "guid";
      packageName = "guid";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/guid/-/guid-0.0.12.tgz";
        sha1 = "9137c52b185f7de12490b9bebcc1660b9025fe0c";
      };
    };
    "log-symbols-1.0.2" = {
      name = "log-symbols";
      packageName = "log-symbols";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/log-symbols/-/log-symbols-1.0.2.tgz";
        sha1 = "376ff7b58ea3086a0f09facc74617eca501e1a18";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "rimraf-2.5.4" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.5.4.tgz";
        sha1 = "96800093cbf1a0c86bd95b4625467535c29dfa04";
      };
    };
    "semver-5.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.3.0.tgz";
        sha1 = "9b2ce5d3de02d17c6012ad326aa6b4d0cf54f94f";
      };
    };
    "ti-console-0.1.4" = {
      name = "ti-console";
      packageName = "ti-console";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/ti-console/-/ti-console-0.1.4.tgz";
        sha1 = "5275ed0d89c2b67e06031b9f57b6606a5a6b2820";
      };
    };
    "ti-fs-0.1.1" = {
      name = "ti-fs";
      packageName = "ti-fs";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ti-fs/-/ti-fs-0.1.1.tgz";
        sha1 = "98b18e38b9deb5f90dd1e647452a5f7c70fccead";
      };
    };
    "tiapp.xml-0.2.2" = {
      name = "tiapp.xml";
      packageName = "tiapp.xml";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tiapp.xml/-/tiapp.xml-0.2.2.tgz";
        sha1 = "d7d5ec6c4761d1ff2d8d8f6fa98e6efb86667811";
      };
    };
    "titanium-os-0.1.1" = {
      name = "titanium-os";
      packageName = "titanium-os";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/titanium-os/-/titanium-os-0.1.1.tgz";
        sha1 = "ed6fcf767c7848320155880841696f094df6e5c9";
      };
    };
    "titanium-resolve-0.4.0" = {
      name = "titanium-resolve";
      packageName = "titanium-resolve";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/titanium-resolve/-/titanium-resolve-0.4.0.tgz";
        sha1 = "3afef7f2d33d68e06152a484add0e49d8ec3c205";
      };
    };
    "touch-1.0.0" = {
      name = "touch";
      packageName = "touch";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/touch/-/touch-1.0.0.tgz";
        sha1 = "449cbe2dbae5a8c8038e30d71fa0ff464947c4de";
      };
    };
    "update-notifier-0.5.0" = {
      name = "update-notifier";
      packageName = "update-notifier";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/update-notifier/-/update-notifier-0.5.0.tgz";
        sha1 = "07b5dc2066b3627ab3b4f530130f7eddda07a4cc";
      };
    };
    "vm-titanium-0.0.1" = {
      name = "vm-titanium";
      packageName = "vm-titanium";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vm-titanium/-/vm-titanium-0.0.1.tgz";
        sha1 = "7990334ba7134f68760ac940e7ff0efdc7f44f7c";
      };
    };
    "JSONStream-1.1.4" = {
      name = "JSONStream";
      packageName = "JSONStream";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/JSONStream/-/JSONStream-1.1.4.tgz";
        sha1 = "be11a495938e882d277773d11986f3974a8ba37a";
      };
    };
    "assert-1.3.0" = {
      name = "assert";
      packageName = "assert";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert/-/assert-1.3.0.tgz";
        sha1 = "03939a622582a812cc202320a0b9a56c9b815849";
      };
    };
    "browser-pack-5.0.1" = {
      name = "browser-pack";
      packageName = "browser-pack";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-pack/-/browser-pack-5.0.1.tgz";
        sha1 = "4197719b20c6e0aaa09451c5111e53efb6fbc18d";
      };
    };
    "browser-resolve-1.11.2" = {
      name = "browser-resolve";
      packageName = "browser-resolve";
      version = "1.11.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-resolve/-/browser-resolve-1.11.2.tgz";
        sha1 = "8ff09b0a2c421718a1051c260b32e48f442938ce";
      };
    };
    "browserify-zlib-0.1.4" = {
      name = "browserify-zlib";
      packageName = "browserify-zlib";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-zlib/-/browserify-zlib-0.1.4.tgz";
        sha1 = "bb35f8a519f600e0fa6b8485241c979d0141fb2d";
      };
    };
    "buffer-3.6.0" = {
      name = "buffer";
      packageName = "buffer";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-3.6.0.tgz";
        sha1 = "a72c936f77b96bf52f5f7e7b467180628551defb";
      };
    };
    "builtins-0.0.7" = {
      name = "builtins";
      packageName = "builtins";
      version = "0.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtins/-/builtins-0.0.7.tgz";
        sha1 = "355219cd6cf18dbe7c01cc7fd2dce765cfdc549a";
      };
    };
    "commondir-0.0.1" = {
      name = "commondir";
      packageName = "commondir";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commondir/-/commondir-0.0.1.tgz";
        sha1 = "89f00fdcd51b519c578733fec563e6a6da7f5be2";
      };
    };
    "concat-stream-1.4.10" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "1.4.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-1.4.10.tgz";
        sha1 = "acc3bbf5602cb8cc980c6ac840fa7d8603e3ef36";
      };
    };
    "console-browserify-1.1.0" = {
      name = "console-browserify";
      packageName = "console-browserify";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/console-browserify/-/console-browserify-1.1.0.tgz";
        sha1 = "f0241c45730a9fc6323b206dbf38edc741d0bb10";
      };
    };
    "constants-browserify-0.0.1" = {
      name = "constants-browserify";
      packageName = "constants-browserify";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/constants-browserify/-/constants-browserify-0.0.1.tgz";
        sha1 = "92577db527ba6c4cf0a4568d84bc031f441e21f2";
      };
    };
    "crypto-browserify-3.11.0" = {
      name = "crypto-browserify";
      packageName = "crypto-browserify";
      version = "3.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crypto-browserify/-/crypto-browserify-3.11.0.tgz";
        sha1 = "3652a0906ab9b2a7e0c3ce66a408e957a2485522";
      };
    };
    "defined-1.0.0" = {
      name = "defined";
      packageName = "defined";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/defined/-/defined-1.0.0.tgz";
        sha1 = "c98d9bcef75674188e110969151199e39b1fa693";
      };
    };
    "deps-sort-1.3.9" = {
      name = "deps-sort";
      packageName = "deps-sort";
      version = "1.3.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/deps-sort/-/deps-sort-1.3.9.tgz";
        sha1 = "29dfff53e17b36aecae7530adbbbf622c2ed1a71";
      };
    };
    "domain-browser-1.1.7" = {
      name = "domain-browser";
      packageName = "domain-browser";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/domain-browser/-/domain-browser-1.1.7.tgz";
        sha1 = "867aa4b093faa05f1de08c06f4d7b21fdf8698bc";
      };
    };
    "duplexer2-0.0.2" = {
      name = "duplexer2";
      packageName = "duplexer2";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexer2/-/duplexer2-0.0.2.tgz";
        sha1 = "c614dcf67e2fb14995a91711e5a617e8a60a31db";
      };
    };
    "events-1.0.2" = {
      name = "events";
      packageName = "events";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/events/-/events-1.0.2.tgz";
        sha1 = "75849dcfe93d10fb057c30055afdbd51d06a8e24";
      };
    };
    "glob-4.5.3" = {
      name = "glob";
      packageName = "glob";
      version = "4.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-4.5.3.tgz";
        sha1 = "c6cb73d3226c1efef04de3c56d012f03377ee15f";
      };
    };
    "has-1.0.1" = {
      name = "has";
      packageName = "has";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.1.tgz";
        sha1 = "8461733f538b0837c9361e39a9ab9e9704dc2f28";
      };
    };
    "htmlescape-1.1.1" = {
      name = "htmlescape";
      packageName = "htmlescape";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlescape/-/htmlescape-1.1.1.tgz";
        sha1 = "3a03edc2214bca3b66424a3e7959349509cb0351";
      };
    };
    "stream-http-1.7.1" = {
      name = "stream-http";
      packageName = "stream-http";
      version = "1.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-http/-/stream-http-1.7.1.tgz";
        sha1 = "d3d2a6e14c36a38b9dafb199aee7bbc570519978";
      };
    };
    "https-browserify-0.0.1" = {
      name = "https-browserify";
      packageName = "https-browserify";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/https-browserify/-/https-browserify-0.0.1.tgz";
        sha1 = "3f91365cabe60b77ed0ebba24b454e3e09d95a82";
      };
    };
    "insert-module-globals-6.6.3" = {
      name = "insert-module-globals";
      packageName = "insert-module-globals";
      version = "6.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/insert-module-globals/-/insert-module-globals-6.6.3.tgz";
        sha1 = "20638e29a30f9ed1ca2e3a825fbc2cba5246ddfc";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "labeled-stream-splicer-1.0.2" = {
      name = "labeled-stream-splicer";
      packageName = "labeled-stream-splicer";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/labeled-stream-splicer/-/labeled-stream-splicer-1.0.2.tgz";
        sha1 = "4615331537784981e8fd264e1f3a434c4e0ddd65";
      };
    };
    "module-deps-3.9.1" = {
      name = "module-deps";
      packageName = "module-deps";
      version = "3.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/module-deps/-/module-deps-3.9.1.tgz";
        sha1 = "ea75caf9199090d25b0d5512b5acacb96e7f87f3";
      };
    };
    "os-browserify-0.1.2" = {
      name = "os-browserify";
      packageName = "os-browserify";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-browserify/-/os-browserify-0.1.2.tgz";
        sha1 = "49ca0293e0b19590a5f5de10c7f265a617d8fe54";
      };
    };
    "parents-1.0.1" = {
      name = "parents";
      packageName = "parents";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parents/-/parents-1.0.1.tgz";
        sha1 = "fedd4d2bf193a77745fe71e371d73c3307d9c751";
      };
    };
    "path-browserify-0.0.0" = {
      name = "path-browserify";
      packageName = "path-browserify";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-browserify/-/path-browserify-0.0.0.tgz";
        sha1 = "a0b870729aae214005b7d5032ec2cbbb0fb4451a";
      };
    };
    "process-0.11.9" = {
      name = "process";
      packageName = "process";
      version = "0.11.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/process/-/process-0.11.9.tgz";
        sha1 = "7bd5ad21aa6253e7da8682264f1e11d11c0318c1";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "querystring-es3-0.2.1" = {
      name = "querystring-es3";
      packageName = "querystring-es3";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/querystring-es3/-/querystring-es3-0.2.1.tgz";
        sha1 = "9ec61f79049875707d69414596fd907a4d711e73";
      };
    };
    "read-only-stream-1.1.1" = {
      name = "read-only-stream";
      packageName = "read-only-stream";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-only-stream/-/read-only-stream-1.1.1.tgz";
        sha1 = "5da77c799ed1388d3ef88a18471bb5924f8a0ba1";
      };
    };
    "readable-stream-2.1.5" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.1.5.tgz";
        sha1 = "66fa8b720e1438b364681f2ad1a63c618448c9d0";
      };
    };
    "resolve-1.1.7" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.1.7.tgz";
        sha1 = "203114d82ad2c5ed9e8e0411b3932875e889e97b";
      };
    };
    "shasum-1.0.2" = {
      name = "shasum";
      packageName = "shasum";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/shasum/-/shasum-1.0.2.tgz";
        sha1 = "e7012310d8f417f4deb5712150e5678b87ae565f";
      };
    };
    "shell-quote-0.0.1" = {
      name = "shell-quote";
      packageName = "shell-quote";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/shell-quote/-/shell-quote-0.0.1.tgz";
        sha1 = "1a41196f3c0333c482323593d6886ecf153dd986";
      };
    };
    "stream-browserify-2.0.1" = {
      name = "stream-browserify";
      packageName = "stream-browserify";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-browserify/-/stream-browserify-2.0.1.tgz";
        sha1 = "66266ee5f9bdb9940a4e4514cafb43bb71e5c9db";
      };
    };
    "subarg-1.0.0" = {
      name = "subarg";
      packageName = "subarg";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/subarg/-/subarg-1.0.0.tgz";
        sha1 = "f62cf17581e996b48fc965699f54c06ae268b8d2";
      };
    };
    "syntax-error-1.1.6" = {
      name = "syntax-error";
      packageName = "syntax-error";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/syntax-error/-/syntax-error-1.1.6.tgz";
        sha1 = "b4549706d386cc1c1dc7c2423f18579b6cade710";
      };
    };
    "through2-1.1.1" = {
      name = "through2";
      packageName = "through2";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/through2/-/through2-1.1.1.tgz";
        sha1 = "0847cbc4449f3405574dbdccd9bb841b83ac3545";
      };
    };
    "timers-browserify-1.4.2" = {
      name = "timers-browserify";
      packageName = "timers-browserify";
      version = "1.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/timers-browserify/-/timers-browserify-1.4.2.tgz";
        sha1 = "c9c58b575be8407375cb5e2462dacee74359f41d";
      };
    };
    "tty-browserify-0.0.0" = {
      name = "tty-browserify";
      packageName = "tty-browserify";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tty-browserify/-/tty-browserify-0.0.0.tgz";
        sha1 = "a157ba402da24e9bf957f9aa69d524eed42901a6";
      };
    };
    "url-0.10.3" = {
      name = "url";
      packageName = "url";
      version = "0.10.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/url/-/url-0.10.3.tgz";
        sha1 = "021e4d9c7705f21bbf37d03ceb58767402774c64";
      };
    };
    "util-0.10.3" = {
      name = "util";
      packageName = "util";
      version = "0.10.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/util/-/util-0.10.3.tgz";
        sha1 = "7afb1afe50805246489e3db7fe0ed379336ac0f9";
      };
    };
    "vm-browserify-0.0.4" = {
      name = "vm-browserify";
      packageName = "vm-browserify";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/vm-browserify/-/vm-browserify-0.0.4.tgz";
        sha1 = "5d7ea45bbef9e4a6ff65f95438e0a87c357d5a73";
      };
    };
    "jsonparse-1.2.0" = {
      name = "jsonparse";
      packageName = "jsonparse";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonparse/-/jsonparse-1.2.0.tgz";
        sha1 = "5c0c5685107160e72fe7489bddea0b44c2bc67bd";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "combine-source-map-0.6.1" = {
      name = "combine-source-map";
      packageName = "combine-source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/combine-source-map/-/combine-source-map-0.6.1.tgz";
        sha1 = "9b4a09c316033d768e0f11e029fa2730e079ad96";
      };
    };
    "umd-3.0.1" = {
      name = "umd";
      packageName = "umd";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/umd/-/umd-3.0.1.tgz";
        sha1 = "8ae556e11011f63c2596708a8837259f01b3d60e";
      };
    };
    "convert-source-map-1.1.3" = {
      name = "convert-source-map";
      packageName = "convert-source-map";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/convert-source-map/-/convert-source-map-1.1.3.tgz";
        sha1 = "4829c877e9fe49b3161f3bf3673888e204699860";
      };
    };
    "inline-source-map-0.5.0" = {
      name = "inline-source-map";
      packageName = "inline-source-map";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/inline-source-map/-/inline-source-map-0.5.0.tgz";
        sha1 = "4a4c5dd8e4fb5e9b3cda60c822dfadcaee66e0af";
      };
    };
    "lodash.memoize-3.0.4" = {
      name = "lodash.memoize";
      packageName = "lodash.memoize";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.memoize/-/lodash.memoize-3.0.4.tgz";
        sha1 = "2dcbd2c287cbc0a55cc42328bd0c736150d53e3f";
      };
    };
    "source-map-0.4.4" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.4.4.tgz";
        sha1 = "eba4f5da9c0dc999de68032d8b4f76173652036b";
      };
    };
    "amdefine-1.0.0" = {
      name = "amdefine";
      packageName = "amdefine";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/amdefine/-/amdefine-1.0.0.tgz";
        sha1 = "fd17474700cb5cc9c2b709f0be9d23ce3c198c33";
      };
    };
    "pako-0.2.9" = {
      name = "pako";
      packageName = "pako";
      version = "0.2.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/pako/-/pako-0.2.9.tgz";
        sha1 = "f3f7522f4ef782348da8161bad9ecfd51bf83a75";
      };
    };
    "base64-js-0.0.8" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-0.0.8.tgz";
        sha1 = "1101e9544f4a76b1bc3b26d452ca96d7a35e7978";
      };
    };
    "ieee754-1.1.6" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.1.6.tgz";
        sha1 = "2e1013219c6d6712973ec54d981ec19e5579de97";
      };
    };
    "typedarray-0.0.6" = {
      name = "typedarray";
      packageName = "typedarray";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray/-/typedarray-0.0.6.tgz";
        sha1 = "867ac74e3864187b1d3d47d996a78ec5c8830777";
      };
    };
    "readable-stream-1.1.14" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.1.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.1.14.tgz";
        sha1 = "7cf4c54ef648e3813084c636dd2079e166c081d9";
      };
    };
    "date-now-0.1.4" = {
      name = "date-now";
      packageName = "date-now";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/date-now/-/date-now-0.1.4.tgz";
        sha1 = "eaf439fd4d4848ad74e5cc7dbef200672b9e345b";
      };
    };
    "browserify-cipher-1.0.0" = {
      name = "browserify-cipher";
      packageName = "browserify-cipher";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-cipher/-/browserify-cipher-1.0.0.tgz";
        sha1 = "9988244874bf5ed4e28da95666dcd66ac8fc363a";
      };
    };
    "browserify-sign-4.0.0" = {
      name = "browserify-sign";
      packageName = "browserify-sign";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-sign/-/browserify-sign-4.0.0.tgz";
        sha1 = "10773910c3c206d5420a46aad8694f820b85968f";
      };
    };
    "create-ecdh-4.0.0" = {
      name = "create-ecdh";
      packageName = "create-ecdh";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-ecdh/-/create-ecdh-4.0.0.tgz";
        sha1 = "888c723596cdf7612f6498233eebd7a35301737d";
      };
    };
    "create-hash-1.1.2" = {
      name = "create-hash";
      packageName = "create-hash";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hash/-/create-hash-1.1.2.tgz";
        sha1 = "51210062d7bb7479f6c65bb41a92208b1d61abad";
      };
    };
    "create-hmac-1.1.4" = {
      name = "create-hmac";
      packageName = "create-hmac";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hmac/-/create-hmac-1.1.4.tgz";
        sha1 = "d3fb4ba253eb8b3f56e39ea2fbcb8af747bd3170";
      };
    };
    "diffie-hellman-5.0.2" = {
      name = "diffie-hellman";
      packageName = "diffie-hellman";
      version = "5.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/diffie-hellman/-/diffie-hellman-5.0.2.tgz";
        sha1 = "b5835739270cfe26acf632099fded2a07f209e5e";
      };
    };
    "pbkdf2-3.0.4" = {
      name = "pbkdf2";
      packageName = "pbkdf2";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pbkdf2/-/pbkdf2-3.0.4.tgz";
        sha1 = "12c8bfaf920543786a85150b03f68d5f1aa982fc";
      };
    };
    "public-encrypt-4.0.0" = {
      name = "public-encrypt";
      packageName = "public-encrypt";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/public-encrypt/-/public-encrypt-4.0.0.tgz";
        sha1 = "39f699f3a46560dd5ebacbca693caf7c65c18cc6";
      };
    };
    "randombytes-2.0.3" = {
      name = "randombytes";
      packageName = "randombytes";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/randombytes/-/randombytes-2.0.3.tgz";
        sha1 = "674c99760901c3c4112771a31e521dc349cc09ec";
      };
    };
    "browserify-aes-1.0.6" = {
      name = "browserify-aes";
      packageName = "browserify-aes";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-aes/-/browserify-aes-1.0.6.tgz";
        sha1 = "5e7725dbdef1fd5930d4ebab48567ce451c48a0a";
      };
    };
    "browserify-des-1.0.0" = {
      name = "browserify-des";
      packageName = "browserify-des";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-des/-/browserify-des-1.0.0.tgz";
        sha1 = "daa277717470922ed2fe18594118a175439721dd";
      };
    };
    "evp_bytestokey-1.0.0" = {
      name = "evp_bytestokey";
      packageName = "evp_bytestokey";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/evp_bytestokey/-/evp_bytestokey-1.0.0.tgz";
        sha1 = "497b66ad9fef65cd7c08a6180824ba1476b66e53";
      };
    };
    "buffer-xor-1.0.3" = {
      name = "buffer-xor";
      packageName = "buffer-xor";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-xor/-/buffer-xor-1.0.3.tgz";
        sha1 = "26e61ed1422fb70dd42e6e36729ed51d855fe8d9";
      };
    };
    "cipher-base-1.0.2" = {
      name = "cipher-base";
      packageName = "cipher-base";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cipher-base/-/cipher-base-1.0.2.tgz";
        sha1 = "54ac1d1ebdf6a1bcd3559e6f369d72697f2cab8f";
      };
    };
    "des.js-1.0.0" = {
      name = "des.js";
      packageName = "des.js";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/des.js/-/des.js-1.0.0.tgz";
        sha1 = "c074d2e2aa6a8a9a07dbd61f9a15c2cd83ec8ecc";
      };
    };
    "minimalistic-assert-1.0.0" = {
      name = "minimalistic-assert";
      packageName = "minimalistic-assert";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimalistic-assert/-/minimalistic-assert-1.0.0.tgz";
        sha1 = "702be2dda6b37f4836bcb3f5db56641b64a1d3d3";
      };
    };
    "bn.js-4.11.6" = {
      name = "bn.js";
      packageName = "bn.js";
      version = "4.11.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/bn.js/-/bn.js-4.11.6.tgz";
        sha1 = "53344adb14617a13f6e8dd2ce28905d1c0ba3215";
      };
    };
    "browserify-rsa-4.0.1" = {
      name = "browserify-rsa";
      packageName = "browserify-rsa";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-rsa/-/browserify-rsa-4.0.1.tgz";
        sha1 = "21e0abfaf6f2029cf2fafb133567a701d4135524";
      };
    };
    "elliptic-6.3.1" = {
      name = "elliptic";
      packageName = "elliptic";
      version = "6.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/elliptic/-/elliptic-6.3.1.tgz";
        sha1 = "17781f2109ab0ec686b146bdcff5d2e8c6aeceda";
      };
    };
    "parse-asn1-5.0.0" = {
      name = "parse-asn1";
      packageName = "parse-asn1";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-asn1/-/parse-asn1-5.0.0.tgz";
        sha1 = "35060f6d5015d37628c770f4e091a0b5a278bc23";
      };
    };
    "brorand-1.0.5" = {
      name = "brorand";
      packageName = "brorand";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/brorand/-/brorand-1.0.5.tgz";
        sha1 = "07b54ca30286abd1718a0e2a830803efdc9bfa04";
      };
    };
    "hash.js-1.0.3" = {
      name = "hash.js";
      packageName = "hash.js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hash.js/-/hash.js-1.0.3.tgz";
        sha1 = "1332ff00156c0a0ffdd8236013d07b77a0451573";
      };
    };
    "asn1.js-4.8.0" = {
      name = "asn1.js";
      packageName = "asn1.js";
      version = "4.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1.js/-/asn1.js-4.8.0.tgz";
        sha1 = "e0e04e9923319163be46aed9e5378973b161ef13";
      };
    };
    "ripemd160-1.0.1" = {
      name = "ripemd160";
      packageName = "ripemd160";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ripemd160/-/ripemd160-1.0.1.tgz";
        sha1 = "93a4bbd4942bc574b69a8fa57c71de10ecca7d6e";
      };
    };
    "sha.js-2.4.5" = {
      name = "sha.js";
      packageName = "sha.js";
      version = "2.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/sha.js/-/sha.js-2.4.5.tgz";
        sha1 = "27d171efcc82a118b99639ff581660242b506e7c";
      };
    };
    "miller-rabin-4.0.0" = {
      name = "miller-rabin";
      packageName = "miller-rabin";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/miller-rabin/-/miller-rabin-4.0.0.tgz";
        sha1 = "4a62fb1d42933c05583982f4c716f6fb9e6c6d3d";
      };
    };
    "inflight-1.0.5" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.5.tgz";
        sha1 = "db3204cd5a9de2e6cd890b85c6e2f66bcf4f620a";
      };
    };
    "minimatch-2.0.10" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "2.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-2.0.10.tgz";
        sha1 = "8d087c39c6b38c001b97fca7ce6d0e1e80afbac7";
      };
    };
    "once-1.3.3" = {
      name = "once";
      packageName = "once";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.3.3.tgz";
        sha1 = "b2e261557ce4c314ec8304f3fa82663e4297ca20";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "brace-expansion-1.1.6" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.6.tgz";
        sha1 = "7197d7eaa9b87e648390ea61fc66c84427420df9";
      };
    };
    "balanced-match-0.4.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-0.4.2.tgz";
        sha1 = "cb3f3e3c732dc0f01ee70b403f302e61d7709838";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "function-bind-1.1.0" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.0.tgz";
        sha1 = "16176714c801798e4e8f2cf7f7529467bb4a5771";
      };
    };
    "builtin-status-codes-1.0.0" = {
      name = "builtin-status-codes";
      packageName = "builtin-status-codes";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtin-status-codes/-/builtin-status-codes-1.0.0.tgz";
        sha1 = "30637ee262978ac07174e16d7f82f0ad06e085ad";
      };
    };
    "foreach-2.0.5" = {
      name = "foreach";
      packageName = "foreach";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/foreach/-/foreach-2.0.5.tgz";
        sha1 = "0bee005018aeb260d0a3af3ae658dd0136ec1b99";
      };
    };
    "indexof-0.0.1" = {
      name = "indexof";
      packageName = "indexof";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/indexof/-/indexof-0.0.1.tgz";
        sha1 = "82dc336d232b9062179d05ab3293a66059fd435d";
      };
    };
    "object-keys-1.0.11" = {
      name = "object-keys";
      packageName = "object-keys";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-keys/-/object-keys-1.0.11.tgz";
        sha1 = "c54601778ad560f1142ce0e01bcca8b56d13426d";
      };
    };
    "is-buffer-1.1.4" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-1.1.4.tgz";
        sha1 = "cfc86ccd5dc5a52fa80489111c6920c457e2d98b";
      };
    };
    "lexical-scope-1.2.0" = {
      name = "lexical-scope";
      packageName = "lexical-scope";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lexical-scope/-/lexical-scope-1.2.0.tgz";
        sha1 = "fcea5edc704a4b3a8796cdca419c3a0afaf22df4";
      };
    };
    "astw-2.0.0" = {
      name = "astw";
      packageName = "astw";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/astw/-/astw-2.0.0.tgz";
        sha1 = "08121ac8288d35611c0ceec663f6cd545604897d";
      };
    };
    "acorn-1.2.2" = {
      name = "acorn";
      packageName = "acorn";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-1.2.2.tgz";
        sha1 = "c8ce27de0acc76d896d2b1fad3df588d9e82f014";
      };
    };
    "stream-splicer-1.3.2" = {
      name = "stream-splicer";
      packageName = "stream-splicer";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-splicer/-/stream-splicer-1.3.2.tgz";
        sha1 = "3c0441be15b9bf4e226275e6dc83964745546661";
      };
    };
    "readable-wrap-1.0.0" = {
      name = "readable-wrap";
      packageName = "readable-wrap";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-wrap/-/readable-wrap-1.0.0.tgz";
        sha1 = "3b5a211c631e12303a54991c806c17e7ae206bff";
      };
    };
    "detective-4.3.1" = {
      name = "detective";
      packageName = "detective";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/detective/-/detective-4.3.1.tgz";
        sha1 = "9fb06dd1ee8f0ea4dbcc607cda39d9ce1d4f726f";
      };
    };
    "stream-combiner2-1.0.2" = {
      name = "stream-combiner2";
      packageName = "stream-combiner2";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-combiner2/-/stream-combiner2-1.0.2.tgz";
        sha1 = "ba72a6b50cbfabfa950fc8bc87604bd01eb60671";
      };
    };
    "through2-0.5.1" = {
      name = "through2";
      packageName = "through2";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/through2/-/through2-0.5.1.tgz";
        sha1 = "dfdd012eb9c700e2323fd334f38ac622ab372da7";
      };
    };
    "readable-stream-1.0.34" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.0.34";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.34.tgz";
        sha1 = "125820e34bc842d2f2aaafafe4c2916ee32c157c";
      };
    };
    "xtend-3.0.0" = {
      name = "xtend";
      packageName = "xtend";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-3.0.0.tgz";
        sha1 = "5cce7407baf642cba7becda568111c493f59665a";
      };
    };
    "path-platform-0.11.15" = {
      name = "path-platform";
      packageName = "path-platform";
      version = "0.11.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-platform/-/path-platform-0.11.15.tgz";
        sha1 = "e864217f74c36850f0852b78dc7bf7d4a5721bf2";
      };
    };
    "buffer-shims-1.0.0" = {
      name = "buffer-shims";
      packageName = "buffer-shims";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-shims/-/buffer-shims-1.0.0.tgz";
        sha1 = "9978ce317388c649ad8793028c3477ef044a8b51";
      };
    };
    "json-stable-stringify-0.0.1" = {
      name = "json-stable-stringify";
      packageName = "json-stable-stringify";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stable-stringify/-/json-stable-stringify-0.0.1.tgz";
        sha1 = "611c23e814db375527df851193db59dd2af27f45";
      };
    };
    "jsonify-0.0.0" = {
      name = "jsonify";
      packageName = "jsonify";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonify/-/jsonify-0.0.0.tgz";
        sha1 = "2c74b6ee41d93ca51b7b5aaee8f503631d252a73";
      };
    };
    "acorn-2.7.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "2.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-2.7.0.tgz";
        sha1 = "ab6e7d9d886aaca8b085bc3312b79a198433f0e7";
      };
    };
    "punycode-1.3.2" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.3.2.tgz";
        sha1 = "9653a036fb7c1ee42342f2325cceefea3926c48d";
      };
    };
    "querystring-0.2.0" = {
      name = "querystring";
      packageName = "querystring";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/querystring/-/querystring-0.2.0.tgz";
        sha1 = "b209849203bb25df820da756e747005878521620";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "glob-7.0.6" = {
      name = "glob";
      packageName = "glob";
      version = "7.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.0.6.tgz";
        sha1 = "211bafaf49e525b8cd93260d14ab136152b3f57a";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "minimatch-3.0.3" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.3.tgz";
        sha1 = "2a4e4090b96b2db06a9d7df01055a62a77c9b774";
      };
    };
    "path-is-absolute-1.0.0" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.0.tgz";
        sha1 = "263dada66ab3f2fb10bf7f9d24dd8f3e570ef912";
      };
    };
    "xmldom-0.1.22" = {
      name = "xmldom";
      packageName = "xmldom";
      version = "0.1.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmldom/-/xmldom-0.1.22.tgz";
        sha1 = "10de4e5e964981f03c8cc72fadc08d14b6c3aa26";
      };
    };
    "pretty-data2-0.40.1" = {
      name = "pretty-data2";
      packageName = "pretty-data2";
      version = "0.40.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pretty-data2/-/pretty-data2-0.40.1.tgz";
        sha1 = "e7a1f8a0df9a772b378cbab4c978893ed6fe2328";
      };
    };
    "resolve-0.7.4" = {
      name = "resolve";
      packageName = "resolve";
      version = "0.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-0.7.4.tgz";
        sha1 = "395a9ef9e873fbfe12bd14408bd91bb936003d69";
      };
    };
    "nopt-1.0.10" = {
      name = "nopt";
      packageName = "nopt";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-1.0.10.tgz";
        sha1 = "6ddd21bd2a31417b92727dd585f8a6f37608ebee";
      };
    };
    "abbrev-1.0.9" = {
      name = "abbrev";
      packageName = "abbrev";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-1.0.9.tgz";
        sha1 = "91b4792588a7738c25f35dd6f63752a2f8776135";
      };
    };
    "configstore-1.4.0" = {
      name = "configstore";
      packageName = "configstore";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/configstore/-/configstore-1.4.0.tgz";
        sha1 = "c35781d0501d268c25c54b8b17f6240e8a4fb021";
      };
    };
    "is-npm-1.0.0" = {
      name = "is-npm";
      packageName = "is-npm";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-npm/-/is-npm-1.0.0.tgz";
        sha1 = "f2fb63a65e4905b406c86072765a1a4dc793b9f4";
      };
    };
    "latest-version-1.0.1" = {
      name = "latest-version";
      packageName = "latest-version";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/latest-version/-/latest-version-1.0.1.tgz";
        sha1 = "72cfc46e3e8d1be651e1ebb54ea9f6ea96f374bb";
      };
    };
    "repeating-1.1.3" = {
      name = "repeating";
      packageName = "repeating";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeating/-/repeating-1.1.3.tgz";
        sha1 = "3d4114218877537494f97f77f9785fab810fa4ac";
      };
    };
    "semver-diff-2.1.0" = {
      name = "semver-diff";
      packageName = "semver-diff";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver-diff/-/semver-diff-2.1.0.tgz";
        sha1 = "4bbb8437c8d37e4b0cf1a68fd726ec6d645d6d36";
      };
    };
    "string-length-1.0.1" = {
      name = "string-length";
      packageName = "string-length";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-length/-/string-length-1.0.1.tgz";
        sha1 = "56970fb1c38558e9e70b728bf3de269ac45adfac";
      };
    };
    "graceful-fs-4.1.6" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.6.tgz";
        sha1 = "514c38772b31bee2e08bedc21a0aeb3abf54c19e";
      };
    };
    "object-assign-4.1.0" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.0.tgz";
        sha1 = "7a3b3d0e98063d43f4c03f2e8ae6cd51a86883a0";
      };
    };
    "os-tmpdir-1.0.1" = {
      name = "os-tmpdir";
      packageName = "os-tmpdir";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-tmpdir/-/os-tmpdir-1.0.1.tgz";
        sha1 = "e9b423a1edaf479882562e92ed71d7743a071b6e";
      };
    };
    "osenv-0.1.3" = {
      name = "osenv";
      packageName = "osenv";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/osenv/-/osenv-0.1.3.tgz";
        sha1 = "83cf05c6d6458fc4d5ac6362ea325d92f2754217";
      };
    };
    "uuid-2.0.2" = {
      name = "uuid";
      packageName = "uuid";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-2.0.2.tgz";
        sha1 = "48bd5698f0677e3c7901a1c46ef15b1643794726";
      };
    };
    "write-file-atomic-1.2.0" = {
      name = "write-file-atomic";
      packageName = "write-file-atomic";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/write-file-atomic/-/write-file-atomic-1.2.0.tgz";
        sha1 = "14c66d4e4cb3ca0565c28cf3b7a6f3e4d5938fab";
      };
    };
    "xdg-basedir-2.0.0" = {
      name = "xdg-basedir";
      packageName = "xdg-basedir";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xdg-basedir/-/xdg-basedir-2.0.0.tgz";
        sha1 = "edbc903cc385fc04523d966a335504b5504d1bd2";
      };
    };
    "os-homedir-1.0.1" = {
      name = "os-homedir";
      packageName = "os-homedir";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-homedir/-/os-homedir-1.0.1.tgz";
        sha1 = "0d62bdf44b916fd3bbdcf2cab191948fb094f007";
      };
    };
    "imurmurhash-0.1.4" = {
      name = "imurmurhash";
      packageName = "imurmurhash";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/imurmurhash/-/imurmurhash-0.1.4.tgz";
        sha1 = "9218b9b2b928a238b13dc4fb6b6d576f231453ea";
      };
    };
    "slide-1.1.6" = {
      name = "slide";
      packageName = "slide";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/slide/-/slide-1.1.6.tgz";
        sha1 = "56eb027d65b4d2dce6cb2e2d32c4d4afc9e1d707";
      };
    };
    "package-json-1.2.0" = {
      name = "package-json";
      packageName = "package-json";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/package-json/-/package-json-1.2.0.tgz";
        sha1 = "c8ecac094227cdf76a316874ed05e27cc939a0e0";
      };
    };
    "got-3.3.1" = {
      name = "got";
      packageName = "got";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/got/-/got-3.3.1.tgz";
        sha1 = "e5d0ed4af55fc3eef4d56007769d98192bcb2eca";
      };
    };
    "registry-url-3.1.0" = {
      name = "registry-url";
      packageName = "registry-url";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/registry-url/-/registry-url-3.1.0.tgz";
        sha1 = "3d4ef870f73dde1d77f0cf9a381432444e174942";
      };
    };
    "duplexify-3.4.5" = {
      name = "duplexify";
      packageName = "duplexify";
      version = "3.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexify/-/duplexify-3.4.5.tgz";
        sha1 = "0e7e287a775af753bf57e6e7b7f21f183f6c3a53";
      };
    };
    "infinity-agent-2.0.3" = {
      name = "infinity-agent";
      packageName = "infinity-agent";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/infinity-agent/-/infinity-agent-2.0.3.tgz";
        sha1 = "45e0e2ff7a9eb030b27d62b74b3744b7a7ac4216";
      };
    };
    "is-redirect-1.0.0" = {
      name = "is-redirect";
      packageName = "is-redirect";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-redirect/-/is-redirect-1.0.0.tgz";
        sha1 = "1d03dded53bd8db0f30c26e4f95d36fc7c87dc24";
      };
    };
    "is-stream-1.1.0" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-1.1.0.tgz";
        sha1 = "12d4a3dd4e68e0b79ceb8dbc84173ae80d91ca44";
      };
    };
    "lowercase-keys-1.0.0" = {
      name = "lowercase-keys";
      packageName = "lowercase-keys";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lowercase-keys/-/lowercase-keys-1.0.0.tgz";
        sha1 = "4e3366b39e7f5457e35f1324bdf6f88d0bfc7306";
      };
    };
    "nested-error-stacks-1.0.2" = {
      name = "nested-error-stacks";
      packageName = "nested-error-stacks";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/nested-error-stacks/-/nested-error-stacks-1.0.2.tgz";
        sha1 = "19f619591519f096769a5ba9a86e6eeec823c3cf";
      };
    };
    "object-assign-3.0.0" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-3.0.0.tgz";
        sha1 = "9bedd5ca0897949bca47e7ff408062d549f587f2";
      };
    };
    "prepend-http-1.0.4" = {
      name = "prepend-http";
      packageName = "prepend-http";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/prepend-http/-/prepend-http-1.0.4.tgz";
        sha1 = "d4f4562b0ce3696e41ac52d0e002e57a635dc6dc";
      };
    };
    "read-all-stream-3.1.0" = {
      name = "read-all-stream";
      packageName = "read-all-stream";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-all-stream/-/read-all-stream-3.1.0.tgz";
        sha1 = "35c3e177f2078ef789ee4bfafa4373074eaef4fa";
      };
    };
    "timed-out-2.0.0" = {
      name = "timed-out";
      packageName = "timed-out";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/timed-out/-/timed-out-2.0.0.tgz";
        sha1 = "f38b0ae81d3747d628001f41dafc652ace671c0a";
      };
    };
    "end-of-stream-1.0.0" = {
      name = "end-of-stream";
      packageName = "end-of-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.0.0.tgz";
        sha1 = "d4596e702734a93e40e9af864319eabd99ff2f0e";
      };
    };
    "stream-shift-1.0.0" = {
      name = "stream-shift";
      packageName = "stream-shift";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-shift/-/stream-shift-1.0.0.tgz";
        sha1 = "d5c752825e5367e786f78e18e445ea223a155952";
      };
    };
    "rc-1.1.6" = {
      name = "rc";
      packageName = "rc";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/rc/-/rc-1.1.6.tgz";
        sha1 = "43651b76b6ae53b5c802f1151fa3fc3b059969c9";
      };
    };
    "deep-extend-0.4.1" = {
      name = "deep-extend";
      packageName = "deep-extend";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-extend/-/deep-extend-0.4.1.tgz";
        sha1 = "efe4113d08085f4e6f9687759810f807469e2253";
      };
    };
    "ini-1.3.4" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.4.tgz";
        sha1 = "0537cb79daf59b59a1a517dff706c86ec039162e";
      };
    };
    "strip-json-comments-1.0.4" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-1.0.4.tgz";
        sha1 = "1e15fbcac97d3ee99bf2d73b4c656b082bbafb91";
      };
    };
    "is-finite-1.0.1" = {
      name = "is-finite";
      packageName = "is-finite";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-finite/-/is-finite-1.0.1.tgz";
        sha1 = "6438603eaebe2793948ff4a4262ec8db3d62597b";
      };
    };
    "number-is-nan-1.0.0" = {
      name = "number-is-nan";
      packageName = "number-is-nan";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/number-is-nan/-/number-is-nan-1.0.0.tgz";
        sha1 = "c020f529c5282adfdd233d91d4b181c3d686dc4b";
      };
    };
  };
in
{
  titaniumifier = nodeEnv.buildNodePackage {
    name = "titaniumifier";
    packageName = "titaniumifier";
    version = "1.5.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/titaniumifier/-/titaniumifier-1.5.1.tgz";
      sha1 = "2fea9938941b770a208880f6c4638561839b0323";
    };
    dependencies = [
      sources."adm-zip-0.4.7"
      sources."bluebird-2.11.0"
      (sources."browserify-11.2.0" // {
        dependencies = [
          (sources."JSONStream-1.1.4" // {
            dependencies = [
              sources."jsonparse-1.2.0"
              sources."through-2.3.8"
            ];
          })
          sources."assert-1.3.0"
          (sources."browser-pack-5.0.1" // {
            dependencies = [
              (sources."combine-source-map-0.6.1" // {
                dependencies = [
                  sources."convert-source-map-1.1.3"
                  sources."inline-source-map-0.5.0"
                  sources."lodash.memoize-3.0.4"
                  (sources."source-map-0.4.4" // {
                    dependencies = [
                      sources."amdefine-1.0.0"
                    ];
                  })
                ];
              })
              sources."umd-3.0.1"
            ];
          })
          sources."browser-resolve-1.11.2"
          (sources."browserify-zlib-0.1.4" // {
            dependencies = [
              sources."pako-0.2.9"
            ];
          })
          (sources."buffer-3.6.0" // {
            dependencies = [
              sources."base64-js-0.0.8"
              sources."ieee754-1.1.6"
              sources."isarray-1.0.0"
            ];
          })
          sources."builtins-0.0.7"
          sources."commondir-0.0.1"
          (sources."concat-stream-1.4.10" // {
            dependencies = [
              sources."typedarray-0.0.6"
              (sources."readable-stream-1.1.14" // {
                dependencies = [
                  sources."core-util-is-1.0.2"
                ];
              })
            ];
          })
          (sources."console-browserify-1.1.0" // {
            dependencies = [
              sources."date-now-0.1.4"
            ];
          })
          sources."constants-browserify-0.0.1"
          (sources."crypto-browserify-3.11.0" // {
            dependencies = [
              (sources."browserify-cipher-1.0.0" // {
                dependencies = [
                  (sources."browserify-aes-1.0.6" // {
                    dependencies = [
                      sources."buffer-xor-1.0.3"
                      sources."cipher-base-1.0.2"
                    ];
                  })
                  (sources."browserify-des-1.0.0" // {
                    dependencies = [
                      sources."cipher-base-1.0.2"
                      (sources."des.js-1.0.0" // {
                        dependencies = [
                          sources."minimalistic-assert-1.0.0"
                        ];
                      })
                    ];
                  })
                  sources."evp_bytestokey-1.0.0"
                ];
              })
              (sources."browserify-sign-4.0.0" // {
                dependencies = [
                  sources."bn.js-4.11.6"
                  sources."browserify-rsa-4.0.1"
                  (sources."elliptic-6.3.1" // {
                    dependencies = [
                      sources."brorand-1.0.5"
                      sources."hash.js-1.0.3"
                    ];
                  })
                  (sources."parse-asn1-5.0.0" // {
                    dependencies = [
                      (sources."asn1.js-4.8.0" // {
                        dependencies = [
                          sources."minimalistic-assert-1.0.0"
                        ];
                      })
                      (sources."browserify-aes-1.0.6" // {
                        dependencies = [
                          sources."buffer-xor-1.0.3"
                          sources."cipher-base-1.0.2"
                        ];
                      })
                      sources."evp_bytestokey-1.0.0"
                    ];
                  })
                ];
              })
              (sources."create-ecdh-4.0.0" // {
                dependencies = [
                  sources."bn.js-4.11.6"
                  (sources."elliptic-6.3.1" // {
                    dependencies = [
                      sources."brorand-1.0.5"
                      sources."hash.js-1.0.3"
                    ];
                  })
                ];
              })
              (sources."create-hash-1.1.2" // {
                dependencies = [
                  sources."cipher-base-1.0.2"
                  sources."ripemd160-1.0.1"
                  sources."sha.js-2.4.5"
                ];
              })
              sources."create-hmac-1.1.4"
              (sources."diffie-hellman-5.0.2" // {
                dependencies = [
                  sources."bn.js-4.11.6"
                  (sources."miller-rabin-4.0.0" // {
                    dependencies = [
                      sources."brorand-1.0.5"
                    ];
                  })
                ];
              })
              sources."pbkdf2-3.0.4"
              (sources."public-encrypt-4.0.0" // {
                dependencies = [
                  sources."bn.js-4.11.6"
                  sources."browserify-rsa-4.0.1"
                  (sources."parse-asn1-5.0.0" // {
                    dependencies = [
                      (sources."asn1.js-4.8.0" // {
                        dependencies = [
                          sources."minimalistic-assert-1.0.0"
                        ];
                      })
                      (sources."browserify-aes-1.0.6" // {
                        dependencies = [
                          sources."buffer-xor-1.0.3"
                          sources."cipher-base-1.0.2"
                        ];
                      })
                      sources."evp_bytestokey-1.0.0"
                    ];
                  })
                ];
              })
              sources."randombytes-2.0.3"
            ];
          })
          sources."defined-1.0.0"
          sources."deps-sort-1.3.9"
          sources."domain-browser-1.1.7"
          (sources."duplexer2-0.0.2" // {
            dependencies = [
              (sources."readable-stream-1.1.14" // {
                dependencies = [
                  sources."core-util-is-1.0.2"
                ];
              })
            ];
          })
          sources."events-1.0.2"
          (sources."glob-4.5.3" // {
            dependencies = [
              (sources."inflight-1.0.5" // {
                dependencies = [
                  sources."wrappy-1.0.2"
                ];
              })
              (sources."minimatch-2.0.10" // {
                dependencies = [
                  (sources."brace-expansion-1.1.6" // {
                    dependencies = [
                      sources."balanced-match-0.4.2"
                      sources."concat-map-0.0.1"
                    ];
                  })
                ];
              })
              (sources."once-1.3.3" // {
                dependencies = [
                  sources."wrappy-1.0.2"
                ];
              })
            ];
          })
          (sources."has-1.0.1" // {
            dependencies = [
              sources."function-bind-1.1.0"
            ];
          })
          sources."htmlescape-1.1.1"
          (sources."stream-http-1.7.1" // {
            dependencies = [
              sources."builtin-status-codes-1.0.0"
              sources."foreach-2.0.5"
              sources."indexof-0.0.1"
              sources."object-keys-1.0.11"
            ];
          })
          sources."https-browserify-0.0.1"
          sources."inherits-2.0.1"
          (sources."insert-module-globals-6.6.3" // {
            dependencies = [
              (sources."combine-source-map-0.6.1" // {
                dependencies = [
                  sources."convert-source-map-1.1.3"
                  sources."inline-source-map-0.5.0"
                  sources."lodash.memoize-3.0.4"
                  (sources."source-map-0.4.4" // {
                    dependencies = [
                      sources."amdefine-1.0.0"
                    ];
                  })
                ];
              })
              sources."is-buffer-1.1.4"
              (sources."lexical-scope-1.2.0" // {
                dependencies = [
                  (sources."astw-2.0.0" // {
                    dependencies = [
                      sources."acorn-1.2.2"
                    ];
                  })
                ];
              })
            ];
          })
          sources."isarray-0.0.1"
          (sources."labeled-stream-splicer-1.0.2" // {
            dependencies = [
              (sources."stream-splicer-1.3.2" // {
                dependencies = [
                  (sources."readable-stream-1.1.14" // {
                    dependencies = [
                      sources."core-util-is-1.0.2"
                    ];
                  })
                  sources."readable-wrap-1.0.0"
                  sources."indexof-0.0.1"
                ];
              })
            ];
          })
          (sources."module-deps-3.9.1" // {
            dependencies = [
              (sources."detective-4.3.1" // {
                dependencies = [
                  sources."acorn-1.2.2"
                ];
              })
              (sources."readable-stream-1.1.14" // {
                dependencies = [
                  sources."core-util-is-1.0.2"
                ];
              })
              (sources."stream-combiner2-1.0.2" // {
                dependencies = [
                  (sources."through2-0.5.1" // {
                    dependencies = [
                      (sources."readable-stream-1.0.34" // {
                        dependencies = [
                          sources."core-util-is-1.0.2"
                        ];
                      })
                      sources."xtend-3.0.0"
                    ];
                  })
                ];
              })
            ];
          })
          sources."os-browserify-0.1.2"
          (sources."parents-1.0.1" // {
            dependencies = [
              sources."path-platform-0.11.15"
            ];
          })
          sources."path-browserify-0.0.0"
          sources."process-0.11.9"
          sources."punycode-1.4.1"
          sources."querystring-es3-0.2.1"
          (sources."read-only-stream-1.1.1" // {
            dependencies = [
              (sources."readable-stream-1.1.14" // {
                dependencies = [
                  sources."core-util-is-1.0.2"
                ];
              })
              sources."readable-wrap-1.0.0"
            ];
          })
          (sources."readable-stream-2.1.5" // {
            dependencies = [
              sources."buffer-shims-1.0.0"
              sources."core-util-is-1.0.2"
              sources."isarray-1.0.0"
              sources."process-nextick-args-1.0.7"
              sources."util-deprecate-1.0.2"
            ];
          })
          sources."resolve-1.1.7"
          (sources."shasum-1.0.2" // {
            dependencies = [
              (sources."json-stable-stringify-0.0.1" // {
                dependencies = [
                  sources."jsonify-0.0.0"
                ];
              })
              sources."sha.js-2.4.5"
            ];
          })
          sources."shell-quote-0.0.1"
          sources."stream-browserify-2.0.1"
          sources."string_decoder-0.10.31"
          (sources."subarg-1.0.0" // {
            dependencies = [
              sources."minimist-1.2.0"
            ];
          })
          (sources."syntax-error-1.1.6" // {
            dependencies = [
              sources."acorn-2.7.0"
            ];
          })
          (sources."through2-1.1.1" // {
            dependencies = [
              (sources."readable-stream-1.1.14" // {
                dependencies = [
                  sources."core-util-is-1.0.2"
                ];
              })
            ];
          })
          sources."timers-browserify-1.4.2"
          sources."tty-browserify-0.0.0"
          (sources."url-0.10.3" // {
            dependencies = [
              sources."punycode-1.3.2"
              sources."querystring-0.2.0"
            ];
          })
          sources."util-0.10.3"
          (sources."vm-browserify-0.0.4" // {
            dependencies = [
              sources."indexof-0.0.1"
            ];
          })
          sources."xtend-4.0.1"
        ];
      })
      (sources."commander-2.9.0" // {
        dependencies = [
          sources."graceful-readlink-1.0.1"
        ];
      })
      sources."guid-0.0.12"
      (sources."log-symbols-1.0.2" // {
        dependencies = [
          (sources."chalk-1.1.3" // {
            dependencies = [
              sources."ansi-styles-2.2.1"
              sources."escape-string-regexp-1.0.5"
              (sources."has-ansi-2.0.0" // {
                dependencies = [
                  sources."ansi-regex-2.0.0"
                ];
              })
              (sources."strip-ansi-3.0.1" // {
                dependencies = [
                  sources."ansi-regex-2.0.0"
                ];
              })
              sources."supports-color-2.0.0"
            ];
          })
        ];
      })
      (sources."mkdirp-0.5.1" // {
        dependencies = [
          sources."minimist-0.0.8"
        ];
      })
      (sources."rimraf-2.5.4" // {
        dependencies = [
          (sources."glob-7.0.6" // {
            dependencies = [
              sources."fs.realpath-1.0.0"
              (sources."inflight-1.0.5" // {
                dependencies = [
                  sources."wrappy-1.0.2"
                ];
              })
              sources."inherits-2.0.1"
              (sources."minimatch-3.0.3" // {
                dependencies = [
                  (sources."brace-expansion-1.1.6" // {
                    dependencies = [
                      sources."balanced-match-0.4.2"
                      sources."concat-map-0.0.1"
                    ];
                  })
                ];
              })
              (sources."once-1.3.3" // {
                dependencies = [
                  sources."wrappy-1.0.2"
                ];
              })
              sources."path-is-absolute-1.0.0"
            ];
          })
        ];
      })
      sources."semver-5.3.0"
      (sources."ti-console-0.1.4" // {
        dependencies = [
          sources."date-now-0.1.4"
        ];
      })
      sources."ti-fs-0.1.1"
      (sources."tiapp.xml-0.2.2" // {
        dependencies = [
          sources."xmldom-0.1.22"
          sources."pretty-data2-0.40.1"
        ];
      })
      sources."titanium-os-0.1.1"
      (sources."titanium-resolve-0.4.0" // {
        dependencies = [
          sources."resolve-0.7.4"
        ];
      })
      (sources."touch-1.0.0" // {
        dependencies = [
          (sources."nopt-1.0.10" // {
            dependencies = [
              sources."abbrev-1.0.9"
            ];
          })
        ];
      })
      (sources."update-notifier-0.5.0" // {
        dependencies = [
          (sources."chalk-1.1.3" // {
            dependencies = [
              sources."ansi-styles-2.2.1"
              sources."escape-string-regexp-1.0.5"
              (sources."has-ansi-2.0.0" // {
                dependencies = [
                  sources."ansi-regex-2.0.0"
                ];
              })
              (sources."strip-ansi-3.0.1" // {
                dependencies = [
                  sources."ansi-regex-2.0.0"
                ];
              })
              sources."supports-color-2.0.0"
            ];
          })
          (sources."configstore-1.4.0" // {
            dependencies = [
              sources."graceful-fs-4.1.6"
              sources."object-assign-4.1.0"
              sources."os-tmpdir-1.0.1"
              (sources."osenv-0.1.3" // {
                dependencies = [
                  sources."os-homedir-1.0.1"
                ];
              })
              sources."uuid-2.0.2"
              (sources."write-file-atomic-1.2.0" // {
                dependencies = [
                  sources."imurmurhash-0.1.4"
                  sources."slide-1.1.6"
                ];
              })
              (sources."xdg-basedir-2.0.0" // {
                dependencies = [
                  sources."os-homedir-1.0.1"
                ];
              })
            ];
          })
          sources."is-npm-1.0.0"
          (sources."latest-version-1.0.1" // {
            dependencies = [
              (sources."package-json-1.2.0" // {
                dependencies = [
                  (sources."got-3.3.1" // {
                    dependencies = [
                      (sources."duplexify-3.4.5" // {
                        dependencies = [
                          (sources."end-of-stream-1.0.0" // {
                            dependencies = [
                              (sources."once-1.3.3" // {
                                dependencies = [
                                  sources."wrappy-1.0.2"
                                ];
                              })
                            ];
                          })
                          sources."inherits-2.0.1"
                          (sources."readable-stream-2.1.5" // {
                            dependencies = [
                              sources."buffer-shims-1.0.0"
                              sources."core-util-is-1.0.2"
                              sources."isarray-1.0.0"
                              sources."process-nextick-args-1.0.7"
                              sources."string_decoder-0.10.31"
                              sources."util-deprecate-1.0.2"
                            ];
                          })
                          sources."stream-shift-1.0.0"
                        ];
                      })
                      sources."infinity-agent-2.0.3"
                      sources."is-redirect-1.0.0"
                      sources."is-stream-1.1.0"
                      sources."lowercase-keys-1.0.0"
                      (sources."nested-error-stacks-1.0.2" // {
                        dependencies = [
                          sources."inherits-2.0.1"
                        ];
                      })
                      sources."object-assign-3.0.0"
                      sources."prepend-http-1.0.4"
                      (sources."read-all-stream-3.1.0" // {
                        dependencies = [
                          (sources."pinkie-promise-2.0.1" // {
                            dependencies = [
                              sources."pinkie-2.0.4"
                            ];
                          })
                          (sources."readable-stream-2.1.5" // {
                            dependencies = [
                              sources."buffer-shims-1.0.0"
                              sources."core-util-is-1.0.2"
                              sources."inherits-2.0.1"
                              sources."isarray-1.0.0"
                              sources."process-nextick-args-1.0.7"
                              sources."string_decoder-0.10.31"
                              sources."util-deprecate-1.0.2"
                            ];
                          })
                        ];
                      })
                      sources."timed-out-2.0.0"
                    ];
                  })
                  (sources."registry-url-3.1.0" // {
                    dependencies = [
                      (sources."rc-1.1.6" // {
                        dependencies = [
                          sources."deep-extend-0.4.1"
                          sources."ini-1.3.4"
                          sources."minimist-1.2.0"
                          sources."strip-json-comments-1.0.4"
                        ];
                      })
                    ];
                  })
                ];
              })
            ];
          })
          (sources."repeating-1.1.3" // {
            dependencies = [
              (sources."is-finite-1.0.1" // {
                dependencies = [
                  sources."number-is-nan-1.0.0"
                ];
              })
            ];
          })
          sources."semver-diff-2.1.0"
          (sources."string-length-1.0.1" // {
            dependencies = [
              (sources."strip-ansi-3.0.1" // {
                dependencies = [
                  sources."ansi-regex-2.0.0"
                ];
              })
            ];
          })
        ];
      })
      sources."vm-titanium-0.0.1"
    ];
    buildInputs = commonBuildInputs;
    meta = {
      description = "Get a Titanium SDK CommonJS module out of a Node package!";
      homepage = "https://github.com/smclab/titaniumifier#readme";
      license = "LGPL2.1";
    };
    production = true;
  };
}